# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Videsh Narine
tagline:          'A Jekyll theme'
description:      'Computer Science Senior at CUNY Queens College'
url:              "https://cybeastfalzar.github.io"
baseurl:          ""

author:
  name:           'Mark Otto'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/CybeastFalzar/CybeastFalzar.github.io
